### ISSUE TITLE
Automatically update to use latest swipl, zlib, emscripten etc.

### ISSUE THREAD

**Issue by jeswr** [SWI-Prolog/npm-swipl-wasm#12]
Over in eye-js we have the following [cron job](https://github.com/eyereasoner/eye-js/blob/main/.github/workflows/update-eye.yml) which updates eye-js to use the latest version of eyereasoner, run CI, and automerge. If all CI passes then a [new release](https://github.com/eyereasoner/eye-js/blob/main/.github/workflows/release.yml) is automatically created.

It would be useful to have a similar script ported over here to keep the distribution of `npm-swipl-wasm` up to date with all of its dependants that are outside of the npm ecosystem:
1. To keep everything up to date
2. To catch problems like https://github.com/SWI-Prolog/swipl-devel/pull/1088#issuecomment-1399651681 straight away via tests run in CI

Happy to help out with this if this is something you are interested in, considering it is largely just porting existing scripts.

**Comment by rla** [comment]
It would be really nice if we could get it running.

The most important part would be getting it running for updating swipl-devel commit/tag. zlib is quite stable and emscripten could be really unstable. Not sure if I would really like to update emscripten since it is the most complex part of the setup and updating it would lose stability and testing value that is from using a stable specific version over a longer period of time.

The biggest issue I see right now is running docker-based build inside Actions. Is this possible? Otherwise the build process should be rewritten to run directly without a container.

**Comment by jeswr** [comment]
> The biggest issue I see right now is running docker-based build inside Actions.

The [official GitHub docs](https://docs.github.com/en/actions/creating-actions/creating-a-docker-container-action#introduction) indicate that they have docker support
