### ISSUE TITLE
[wasm]: TypeError: getWasmTableEntry(...) is not a function

### ISSUE THREAD

**Issue by jeswr** [SWI-Prolog/npm-swipl-wasm#618]
This error occured when `swipl-wasm` was updating to swipl@9.3.6. The full error log can be seen at https://github.com/SWI-Prolog/npm-swipl-wasm/actions/runs/9087848997/job/24990215214?pr=611.

@JanWielemaker any idea what could have caused this?

**Comment by JanWielemaker** [comment]
The log is long.   If this refers to the failing test

     [21/23] trie:gen_compiled2_free ../swipl-devel/build.wasm/src/swipl.js:1

This isssue is resolved with SWI-Prolog/swipl-devel@af3ec2de67efb22c8af95b04926cee7ae08271d5.     This test was added to 9.3.6 after fixing several trie issues due to the recent data representation errors.    Unfortunately one remained that was specific to 32 bit systems.

Probably the simplest is to wait for 9.3.7 for the new npm release.

**Comment by jeswr** [comment]
I bumped to a commit after https://github.com/SWI-Prolog/swipl-devel/commit/af3ec2de67efb22c8af95b04926cee7ae08271d5 and things are now working (https://github.com/SWI-Prolog/npm-swipl-wasm/pull/611).
